# Generated by Django 6.0.4 on 2026-05-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='Player',
            new_name='player',
        ),
    ]
